import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app import safe_json_loads

# Raw text with single backslashes in LaTeX as generated by Gemini
# \frac -> \x0crac (formfeed + rac)
# \tan  -> \x09an (tab + an)
# \sqrt -> \sqrt (backslash + s + q + r + t)
# \alpha -> \alpha (backslash + a + l + p + h + a)
raw_text_math = '[\n  {\n    "question": "Solve $\x0crac{x}{2} + \\sqrt{y} = 10$ and $\x09an\\alpha = 1$",\n    "option_a": "\x0crac{1}{2}",\n    "option_b": "\x0crac{3}{4}",\n    "option_c": "\\sqrt{2}",\n    "option_d": "\\sin\\alpha",\n    "correct_answer": "A"\n  }\n]'

print("Received raw_text_math:")
print(repr(raw_text_math))

res = safe_json_loads(raw_text_math)
print("safe_json_loads result Is None?", res is None)



